"use client";
import Link from "next/link";
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import { DashboardCard, DashboardEmpty, CardError } from "./dashboard-card.tsx";
import { useDashboardAlerts } from "@/lib/client/dashboard.ts";
import { formatMoney } from "@/lib/client/format.ts";
import { formatCount } from "@/lib/client/dashboard-format.ts";
import { AppIcon } from "@/components/ui/app-icon.tsx";
import { Thumb } from "@/components/ui/list-controls.tsx";
import { toCents } from "@/lib/numeric.ts";
import { returnPercentage } from "@/lib/dashboard/insights-calculations.ts";
import type { DashboardInsights } from "@/lib/dashboard/insights-types.ts";
import type { DashboardSummary } from "@/lib/dashboard/types.ts";

export interface CardState { loading: boolean; error?: string; onRetry: () => void }
export function StockAlertsCard({ state, wastage, currency }: { state: CardState; wastage?: string; currency: string }) {
  const alerts = useDashboardAlerts();
  return <section className="ui-panel h-full"><h2 className="text-sm font-semibold">Stock alerts</h2><p className="mb-item mt-tight text-xs text-muted">Current inventory · expiry within 30 days</p>{[
    { label: "Low stock", href: "/inventory/low-stock", query: alerts.lowStock, danger: false },
    { label: "Near expiry", href: "/inventory/near-expiry", query: alerts.nearExpiry, danger: true },
  ].map(({ label, href, query, danger }) => <div key={href}>{query.isError ? <CardError message={`${label} unavailable`} onRetry={() => void query.refetch()} /> : <Link href={href} className="grid min-h-12 grid-cols-[minmax(0,1fr)_auto_1rem] items-center gap-item border-b border-border text-xs"><span>{label}</span><span className="ml-auto"><span className={`rounded-full px-small py-tight ${!query.data?.total ? "bg-surface-muted text-muted" : danger ? "bg-danger/10 text-danger" : "bg-warning/10 text-warning"}`}>{query.data ? formatCount(query.data.total) : "Loading…"}</span></span><AppIcon name="arrow" className="h-4 w-4 shrink-0 text-muted" /></Link>}</div>)}{state.error ? <CardError message={state.error} onRetry={state.onRetry} /> : <Link href="/inventory/wastage" className="flex min-h-12 items-center justify-between gap-item text-xs"><span>Wastage <span className="block text-[10px] text-muted">Selected range</span></span><span className="ml-auto break-words text-right">{state.loading ? "Loading…" : formatMoney(wastage ?? "0.00", currency)}</span><AppIcon name="arrow" className="h-4 w-4 shrink-0 text-muted" /></Link>}</section>;
}
export function DuesCard({ state, data, currency, asOf }: { state: CardState; data?: DashboardInsights["dues"]; currency: string; asOf: string }) {
  return <DashboardCard title="Receivable / Payable" subtitle={`Outstanding through ${asOf}; recorded payments are current`} {...state}>{[
    { label: "Customer due", value: data?.receivable, href: "/reports/due" },
    { label: "Supplier due", value: data?.payable, href: "/reports/payable" },
  ].map((row) => <div key={row.label} className="flex items-center justify-between gap-item border-t border-border py-item"><div className="min-w-0"><p className="text-xs text-muted">{row.label}</p><p className="mt-tight break-words text-lg font-semibold">{formatMoney(row.value ?? "0.00", currency)}</p></div><Link href={`${row.href}?from=1970-01-01&to=${asOf}`} className="inline-flex min-h-11 items-center text-xs text-primary">View</Link></div>)}</DashboardCard>;
}
export function TopProductsTable({ state, products, currency }: { state: CardState; products?: DashboardInsights["products"]; currency: string }) {
  return <DashboardCard title="Top selling products" subtitle="Top 5 by net units sold" info="Line subtotals less recorded return credits; invoice discounts and VAT are not allocated to products." {...state}>{!products?.length ? <DashboardEmpty message="No net product sales in this period yet" invoice /> : <div className="overflow-x-auto"><table className="w-full min-w-[480px] text-left text-xs"><caption className="sr-only">Products ranked by units sold minus returned in the selected period</caption><thead><tr className="bg-surface-muted text-[11px] text-muted"><th className="rounded-l-lg px-item py-item font-medium">Product</th><th className="px-item py-item text-right font-medium">Net units</th><th className="rounded-r-lg px-item py-item text-right font-medium">Revenue</th></tr></thead><tbody>{products.map((product) => <tr key={product.id} className="border-b border-border last:border-0"><td className="px-item py-content"><div className="flex items-center gap-item"><Thumb src={product.imageUrl} name={product.name} size="sm" /><div className="min-w-0 max-w-64"><p className="break-words font-medium">{product.name}{product.isDeleted && <span className="ml-tight text-[10px] text-muted">(archived)</span>}</p><p className="mt-tight break-words text-[10px] text-muted">{product.sku} · Sold {formatCount(product.soldQuantity)} · Returned {formatCount(product.returnedQuantity)}</p></div></div></td><td className="px-item py-content text-right font-semibold">{formatCount(product.netQuantity)}</td><td className="whitespace-nowrap px-item py-content text-right">{formatMoney(product.revenue, currency)}</td></tr>)}</tbody></table></div>}</DashboardCard>;
}
export function RecentInvoicesCard({ state, invoices, currency }: { state: CardState; invoices?: DashboardInsights["invoices"]; currency: string }) {
  return <DashboardCard title="Recent invoices" subtitle="Last 5 in the selected range" action={{ label: "View all", href: "/sales/invoices" }} {...state}>{!invoices?.length ? <DashboardEmpty message="No invoices in this period yet" invoice /> : <ul className="divide-y divide-border">{invoices.map((invoice) => <li key={invoice.id}><Link href={`/sales/invoices/${invoice.id}`} className="flex min-h-16 items-center justify-between gap-item rounded-lg py-item transition hover:bg-surface-muted"><div className="min-w-0"><p className="break-words text-xs font-medium">{invoice.invoiceNo}</p><p className="mt-tight truncate text-[11px] text-muted" title={invoice.customer}>{invoice.customer}</p></div><div className="min-w-0 text-right"><p className="break-words text-xs font-semibold">{formatMoney(invoice.amount, currency)}</p><span className={`mt-tight inline-block rounded-full px-small py-micro text-[10px] ${invoice.status === "completed" ? "bg-success/10 text-success" : "bg-warning/10 text-warning"}`}>{invoice.status === "completed" ? "Completed" : "Draft"}</span></div></Link></li>)}</ul>}</DashboardCard>;
}
const CATEGORY_COLORS = ["var(--chart-sales)", "var(--chart-purchases)", "var(--chart-returns)", "var(--chart-sales-light)", "var(--chart-returns-light)"];
export function CategoryDonut({ state, categories, currency }: { state: CardState; categories?: DashboardInsights["categories"]; currency: string }) {
  const positive = (categories ?? []).map((category, index) => ({ ...category, value: Number(category.revenue), fill: CATEGORY_COLORS[index % CATEGORY_COLORS.length] })).filter((category) => toCents(category.revenue) > BigInt(0));
  return <DashboardCard title="Sales by category" subtitle="Positive net line revenue share · excludes invoice discounts/VAT" {...state}>{!categories?.length ? <DashboardEmpty message="No category sales in this period yet" /> : <div className="grid items-center gap-item sm:grid-cols-[200px_minmax(0,1fr)]">{!positive.length ? <DashboardEmpty message="Only return credits in this period" /> : <div className="h-52" role="img" aria-label="Category sales share; exact signed amounts are listed beside the chart"><ResponsiveContainer width="100%" height="100%"><PieChart accessibilityLayer><Pie data={positive} dataKey="value" nameKey="name" innerRadius={58} outerRadius={85} paddingAngle={3} isAnimationActive={false}>{positive.map((category) => <Cell key={category.id} fill={category.fill} />)}</Pie><Tooltip formatter={(_value, name) => formatMoney(positive.find((category) => category.name === name)?.revenue ?? "0.00", currency)} /></PieChart></ResponsiveContainer></div>}<ul className="max-h-56 space-y-small overflow-y-auto">{categories?.map((category, index) => <li key={category.id} className="flex items-start justify-between gap-item text-xs"><span className="flex min-w-0 items-center gap-small"><span aria-hidden="true" className="h-2 w-2 shrink-0 rounded-full" style={{ background: CATEGORY_COLORS[index % CATEGORY_COLORS.length] }} /><span className="break-words">{category.name}</span></span><span className="shrink-0">{formatMoney(category.revenue, currency)}</span></li>)}</ul></div>}<p className="mt-item text-[10px] text-muted">Return credits may create negative category balances; these are listed but excluded from the donut.</p></DashboardCard>;
}
export function ReturnsSummary({ state, counts, summary, summaryError, onSummaryRetry }: { state: CardState; counts?: DashboardInsights["returns"]; summary?: DashboardSummary; summaryError?: string; onSummaryRetry: () => void }) {
  return <DashboardCard title="Returns summary" subtitle="Credits recorded in the selected range" {...state}>{summaryError ? <CardError message={summaryError} onRetry={onSummaryRetry} /> : !summary ? <p className="text-xs text-muted">Loading return amounts…</p> : <div className="space-y-content">{[
    { label: "Sales returns", amount: summary.totals.salesReturns, total: summary.totals.sales, shareLabel: "of net sales", color: "bg-primary", count: counts?.salesCount, href: "/inventory/returns" },
    { label: "Purchase returns", amount: summary.totals.purchaseReturns, total: summary.totals.purchases, shareLabel: "of purchases", color: "bg-chart-purchases", count: counts?.purchaseCount, href: "/inventory/purchase-returns" },
  ].map((row) => {
    const share = returnPercentage(row.amount, row.total), count = row.count ?? "0";
    return <Link key={row.label} href={row.href} className="block min-h-16 rounded-lg border border-border p-item hover:bg-surface-muted"><div className="flex items-center justify-between gap-item"><div className="min-w-0"><p className="text-xs text-muted">{row.label}</p><p className="mt-tight break-words text-xl font-semibold">{formatMoney(row.amount, summary.currency)}</p></div><span className="shrink-0 rounded-full bg-primary/8 px-small py-tight text-[11px] text-primary">{formatCount(count)} {BigInt(count) === BigInt(1) ? "entry" : "entries"}</span></div>{share ? <div className="mt-item"><div aria-hidden="true" className="h-1 overflow-hidden rounded-full bg-surface-muted"><div className={`h-full rounded-full ${row.color}`} style={{ width: `${share.barPercent}%` }} /></div><p className="mt-compact text-[11px] text-muted">{share.percentage}% {row.shareLabel}</p></div> : <p className="mt-small text-[11px] text-muted">—</p>}</Link>;
  })}<p className="text-[11px] leading-relaxed text-muted">Customer credits include returns against older completed invoices. Supplier returns use original receipt costs.</p></div>}</DashboardCard>;
}
