#!/usr/bin/env -S node
import type { Contract as End } from '../../snapshots/e2bcc2e212e0ef535c15ccacfc3efc36ce5b2f7c26954f970ebe8c096236a85f/contract';
import endContract from '../../snapshots/e2bcc2e212e0ef535c15ccacfc3efc36ce5b2f7c26954f970ebe8c096236a85f/contract.json' with { type: 'json' };
import {
  Migration,
  MigrationCLI,
  checkExpression,
  col,
  fn,
  lit,
  primaryKey,
} from '@prisma/orm-postgres/migration';

export default class M extends Migration<never, End> {
  override readonly endContractJson = endContract;

  override get operations() {
    return [
      this.createSchema({ schema: 'public' }),
      this.createTable({
        schema: 'public',
        table: 'audit_logs',
        columns: [
          col('action', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('entity_id', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('entity_type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('metadata', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('tenant_id', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('user_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'categories',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('image_url', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('is_active', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenant_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'customers',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('is_active', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('phone', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('tenant_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'expense_categories',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('is_active', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenant_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'expenses',
        columns: [
          col('amount', 'numeric(10,2)', {
            notNull: true,
            codecRef: { codecId: 'pg/numeric@1', typeParams: { precision: 10, scale: 2 } },
          }),
          col('category_id', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('created_by', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('expense_date', 'date', { notNull: true, codecRef: { codecId: 'pg/date-string@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('note', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('tenant_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'products',
        columns: [
          col('attributes', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('brand', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('category_id', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('color_id', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('cost_price', 'numeric(10,2)', {
            notNull: true,
            codecRef: { codecId: 'pg/numeric@1', typeParams: { precision: 10, scale: 2 } },
          }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('expiry_date', 'date', { codecRef: { codecId: 'pg/date-string@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('image_url', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('is_deleted', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('sell_price', 'numeric(10,2)', {
            notNull: true,
            codecRef: { codecId: 'pg/numeric@1', typeParams: { precision: 10, scale: 2 } },
          }),
          col('size_id', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('sku', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('stock_qty', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('tenant_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('unit_id', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('weight_id', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'returns',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('created_by', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('quantity', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('reason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('refund_amount', 'numeric(10,2)', {
            notNull: true,
            codecRef: { codecId: 'pg/numeric@1', typeParams: { precision: 10, scale: 2 } },
          }),
          col('sale_item_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('tenant_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'sale_items',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('product_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('quantity', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('sale_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('subtotal', 'numeric(10,2)', {
            notNull: true,
            codecRef: { codecId: 'pg/numeric@1', typeParams: { precision: 10, scale: 2 } },
          }),
          col('tenant_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('unit_cost', 'numeric(10,2)', {
            notNull: true,
            codecRef: { codecId: 'pg/numeric@1', typeParams: { precision: 10, scale: 2 } },
          }),
          col('unit_price', 'numeric(10,2)', {
            notNull: true,
            codecRef: { codecId: 'pg/numeric@1', typeParams: { precision: 10, scale: 2 } },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'sales',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('customer_id', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('discount', 'numeric(10,2)', {
            notNull: true,
            codecRef: { codecId: 'pg/numeric@1', typeParams: { precision: 10, scale: 2 } },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('invoice_no', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('paid_amount', 'numeric(10,2)', {
            notNull: true,
            codecRef: { codecId: 'pg/numeric@1', typeParams: { precision: 10, scale: 2 } },
          }),
          col('payment_method', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('sold_by', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('completed'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('subtotal', 'numeric(10,2)', {
            notNull: true,
            codecRef: { codecId: 'pg/numeric@1', typeParams: { precision: 10, scale: 2 } },
          }),
          col('tenant_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('total_amount', 'numeric(10,2)', {
            notNull: true,
            codecRef: { codecId: 'pg/numeric@1', typeParams: { precision: 10, scale: 2 } },
          }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('vat_amount', 'numeric(10,2)', {
            notNull: true,
            codecRef: { codecId: 'pg/numeric@1', typeParams: { precision: 10, scale: 2 } },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression('sales_status_check_f3fa80dd', "\"status\" IN ('draft', 'completed')"),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'stock_movements',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('created_by', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('note', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('product_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('quantity', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('supplier_id', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('tenant_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('unit_cost', 'numeric(10,2)', {
            codecRef: { codecId: 'pg/numeric@1', typeParams: { precision: 10, scale: 2 } },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'stock_movements_type_check_21048d23',
            "\"type\" IN ('in', 'out', 'adjustment', 'return', 'wastage')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'subscriptions',
        columns: [
          col('amount', 'numeric(10,2)', {
            notNull: true,
            codecRef: { codecId: 'pg/numeric@1', typeParams: { precision: 10, scale: 2 } },
          }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('ends_at', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('plan', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('started_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('status', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('stripe_customer_id', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('stripe_subscription_id', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('tenant_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'subscriptions_plan_check_4446931f',
            "\"plan\" IN ('trial', 'basic', 'pro')",
          ),
          checkExpression(
            'subscriptions_status_check_ce1e5d80',
            "\"status\" IN ('trial', 'active', 'past_due', 'cancelled')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'supplier_payments',
        columns: [
          col('amount', 'numeric(10,2)', {
            notNull: true,
            codecRef: { codecId: 'pg/numeric@1', typeParams: { precision: 10, scale: 2 } },
          }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('created_by', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('note', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('payment_date', 'date', { notNull: true, codecRef: { codecId: 'pg/date-string@1' } }),
          col('supplier_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('tenant_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'suppliers',
        columns: [
          col('address', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('is_active', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('phone', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('tenant_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'tenants',
        columns: [
          col('address', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('currency_symbol', 'text', {
            notNull: true,
            default: lit('BDT'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('invoice_type', 'text', {
            notNull: true,
            default: lit('standard'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('is_active', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('logo_url', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('low_stock_threshold', 'int4', {
            notNull: true,
            default: lit(10),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('max_products', 'int4', {
            notNull: true,
            default: lit(100),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('max_staff', 'int4', {
            notNull: true,
            default: lit(5),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('phone', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('subscription_ends_at', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('subscription_plan', 'text', {
            notNull: true,
            default: lit('trial'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('subscription_status', 'text', {
            notNull: true,
            default: lit('trial'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('trial_ends_at', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('vat_percentage', 'numeric(5,2)', {
            notNull: true,
            codecRef: { codecId: 'pg/numeric@1', typeParams: { precision: 5, scale: 2 } },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'tenants_subscription_plan_check_37ed556f',
            "\"subscription_plan\" IN ('trial', 'basic', 'pro')",
          ),
          checkExpression(
            'tenants_subscription_status_check_5eb10fb3',
            "\"subscription_status\" IN ('trial', 'active', 'past_due', 'cancelled')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'users',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('is_active', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('password_hash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('pin_hash', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('role', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenant_id', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('updated_at', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'users_role_check_8541fdc3',
            "\"role\" IN ('super_admin', 'shop_owner', 'manager', 'staff')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'variant_colors',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenant_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'variant_sizes',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenant_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'variant_units',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenant_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'variant_weights',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('tenant_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'wastage',
        columns: [
          col('created_at', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('created_by', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('loss_amount', 'numeric(10,2)', {
            notNull: true,
            codecRef: { codecId: 'pg/numeric@1', typeParams: { precision: 10, scale: 2 } },
          }),
          col('product_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('quantity', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('reason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('tenant_id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.addUnique({
        schema: 'public',
        table: 'categories',
        constraint: 'categories_tenant_id_name_key',
        columns: ['tenant_id', 'name'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'customers',
        constraint: 'customers_tenant_id_phone_key',
        columns: ['tenant_id', 'phone'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'expense_categories',
        constraint: 'expense_categories_tenant_id_name_key',
        columns: ['tenant_id', 'name'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'products',
        constraint: 'products_tenant_id_sku_key',
        columns: ['tenant_id', 'sku'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'sales',
        constraint: 'sales_tenant_id_invoice_no_key',
        columns: ['tenant_id', 'invoice_no'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'users',
        constraint: 'users_email_key',
        columns: ['email'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'variant_colors',
        constraint: 'variant_colors_tenant_id_name_key',
        columns: ['tenant_id', 'name'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'variant_sizes',
        constraint: 'variant_sizes_tenant_id_name_key',
        columns: ['tenant_id', 'name'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'variant_units',
        constraint: 'variant_units_tenant_id_name_key',
        columns: ['tenant_id', 'name'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'variant_weights',
        constraint: 'variant_weights_tenant_id_name_key',
        columns: ['tenant_id', 'name'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'audit_logs',
        index: 'audit_logs_tenant_id_created_at_idx_282da036',
        columns: ['tenant_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'audit_logs',
        index: 'audit_logs_tenant_id_entity_type_entity_id_idx_9a3991b3',
        columns: ['tenant_id', 'entity_type', 'entity_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'audit_logs',
        index: 'audit_logs_tenant_id_id_idx_621bc114',
        columns: ['tenant_id', 'id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'audit_logs',
        index: 'audit_logs_tenant_id_idx_41c0d441',
        columns: ['tenant_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'audit_logs',
        index: 'audit_logs_user_id_idx_6c952402',
        columns: ['user_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'categories',
        index: 'categories_tenant_id_created_at_idx_282da036',
        columns: ['tenant_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'categories',
        index: 'categories_tenant_id_id_idx_621bc114',
        columns: ['tenant_id', 'id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'categories',
        index: 'categories_tenant_id_idx_41c0d441',
        columns: ['tenant_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'customers',
        index: 'customers_tenant_id_created_at_idx_282da036',
        columns: ['tenant_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'customers',
        index: 'customers_tenant_id_id_idx_621bc114',
        columns: ['tenant_id', 'id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'customers',
        index: 'customers_tenant_id_idx_41c0d441',
        columns: ['tenant_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'expense_categories',
        index: 'expense_categories_tenant_id_created_at_idx_282da036',
        columns: ['tenant_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'expense_categories',
        index: 'expense_categories_tenant_id_id_idx_621bc114',
        columns: ['tenant_id', 'id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'expense_categories',
        index: 'expense_categories_tenant_id_idx_41c0d441',
        columns: ['tenant_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'expenses',
        index: 'expenses_category_id_idx_da7213d4',
        columns: ['category_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'expenses',
        index: 'expenses_created_by_idx_e13bb8bf',
        columns: ['created_by'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'expenses',
        index: 'expenses_tenant_id_category_id_expense_date_idx_668cb898',
        columns: ['tenant_id', 'category_id', 'expense_date'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'expenses',
        index: 'expenses_tenant_id_created_at_idx_282da036',
        columns: ['tenant_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'expenses',
        index: 'expenses_tenant_id_expense_date_idx_c7c260f8',
        columns: ['tenant_id', 'expense_date'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'expenses',
        index: 'expenses_tenant_id_id_idx_621bc114',
        columns: ['tenant_id', 'id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'expenses',
        index: 'expenses_tenant_id_idx_41c0d441',
        columns: ['tenant_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'products',
        index: 'products_category_id_idx_da7213d4',
        columns: ['category_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'products',
        index: 'products_color_id_idx_34d8d0d9',
        columns: ['color_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'products',
        index: 'products_size_id_idx_6a72a89a',
        columns: ['size_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'products',
        index: 'products_tenant_id_created_at_idx_282da036',
        columns: ['tenant_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'products',
        index: 'products_tenant_id_expiry_date_idx_c12c9c08',
        columns: ['tenant_id', 'expiry_date'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'products',
        index: 'products_tenant_id_id_idx_621bc114',
        columns: ['tenant_id', 'id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'products',
        index: 'products_tenant_id_idx_41c0d441',
        columns: ['tenant_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'products',
        index: 'products_tenant_id_stock_qty_idx_786e238a',
        columns: ['tenant_id', 'stock_qty'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'products',
        index: 'products_unit_id_idx_2ad34a08',
        columns: ['unit_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'products',
        index: 'products_weight_id_idx_7c4ea817',
        columns: ['weight_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'returns',
        index: 'returns_created_by_idx_e13bb8bf',
        columns: ['created_by'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'returns',
        index: 'returns_sale_item_id_idx_a3b700e0',
        columns: ['sale_item_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'returns',
        index: 'returns_tenant_id_created_at_idx_282da036',
        columns: ['tenant_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'returns',
        index: 'returns_tenant_id_id_idx_621bc114',
        columns: ['tenant_id', 'id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'returns',
        index: 'returns_tenant_id_idx_41c0d441',
        columns: ['tenant_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'returns',
        index: 'returns_tenant_id_sale_item_id_idx_d3592318',
        columns: ['tenant_id', 'sale_item_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sale_items',
        index: 'sale_items_product_id_idx_22a2b7d2',
        columns: ['product_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sale_items',
        index: 'sale_items_sale_id_idx_43e6ad69',
        columns: ['sale_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sale_items',
        index: 'sale_items_tenant_id_created_at_idx_282da036',
        columns: ['tenant_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sale_items',
        index: 'sale_items_tenant_id_id_idx_621bc114',
        columns: ['tenant_id', 'id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sale_items',
        index: 'sale_items_tenant_id_idx_41c0d441',
        columns: ['tenant_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sale_items',
        index: 'sale_items_tenant_id_product_id_idx_724dd954',
        columns: ['tenant_id', 'product_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sale_items',
        index: 'sale_items_tenant_id_sale_id_idx_608cb4cd',
        columns: ['tenant_id', 'sale_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sales',
        index: 'sales_customer_id_idx_e16dfa6b',
        columns: ['customer_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sales',
        index: 'sales_sold_by_idx_fea6ecde',
        columns: ['sold_by'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sales',
        index: 'sales_tenant_id_created_at_idx_282da036',
        columns: ['tenant_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sales',
        index: 'sales_tenant_id_customer_id_idx_ae98272a',
        columns: ['tenant_id', 'customer_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sales',
        index: 'sales_tenant_id_id_idx_621bc114',
        columns: ['tenant_id', 'id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sales',
        index: 'sales_tenant_id_idx_41c0d441',
        columns: ['tenant_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'sales',
        index: 'sales_tenant_id_status_created_at_idx_d969311a',
        columns: ['tenant_id', 'status', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'stock_movements',
        index: 'stock_movements_created_by_idx_e13bb8bf',
        columns: ['created_by'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'stock_movements',
        index: 'stock_movements_product_id_idx_22a2b7d2',
        columns: ['product_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'stock_movements',
        index: 'stock_movements_supplier_id_idx_c2f51ce2',
        columns: ['supplier_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'stock_movements',
        index: 'stock_movements_tenant_id_created_at_idx_282da036',
        columns: ['tenant_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'stock_movements',
        index: 'stock_movements_tenant_id_id_idx_621bc114',
        columns: ['tenant_id', 'id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'stock_movements',
        index: 'stock_movements_tenant_id_idx_41c0d441',
        columns: ['tenant_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'stock_movements',
        index: 'stock_movements_tenant_id_product_id_created_at_idx_dc928262',
        columns: ['tenant_id', 'product_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'stock_movements',
        index: 'stock_movements_tenant_id_supplier_id_idx_c237d355',
        columns: ['tenant_id', 'supplier_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'subscriptions',
        index: 'subscriptions_stripe_subscription_id_idx_2362abe2',
        columns: ['stripe_subscription_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'subscriptions',
        index: 'subscriptions_tenant_id_created_at_idx_282da036',
        columns: ['tenant_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'subscriptions',
        index: 'subscriptions_tenant_id_id_idx_621bc114',
        columns: ['tenant_id', 'id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'subscriptions',
        index: 'subscriptions_tenant_id_idx_41c0d441',
        columns: ['tenant_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'supplier_payments',
        index: 'sup_pay_tenant_supplier_date_idx_950c0bb8',
        columns: ['tenant_id', 'supplier_id', 'payment_date'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'supplier_payments',
        index: 'supplier_payments_created_by_idx_e13bb8bf',
        columns: ['created_by'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'supplier_payments',
        index: 'supplier_payments_supplier_id_idx_c2f51ce2',
        columns: ['supplier_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'supplier_payments',
        index: 'supplier_payments_tenant_id_created_at_idx_282da036',
        columns: ['tenant_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'supplier_payments',
        index: 'supplier_payments_tenant_id_id_idx_621bc114',
        columns: ['tenant_id', 'id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'supplier_payments',
        index: 'supplier_payments_tenant_id_idx_41c0d441',
        columns: ['tenant_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'suppliers',
        index: 'suppliers_tenant_id_created_at_idx_282da036',
        columns: ['tenant_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'suppliers',
        index: 'suppliers_tenant_id_id_idx_621bc114',
        columns: ['tenant_id', 'id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'suppliers',
        index: 'suppliers_tenant_id_idx_41c0d441',
        columns: ['tenant_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'tenants',
        index: 'tenants_created_at_idx_225d8c0f',
        columns: ['created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'users',
        index: 'users_tenant_id_created_at_idx_282da036',
        columns: ['tenant_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'users',
        index: 'users_tenant_id_id_idx_621bc114',
        columns: ['tenant_id', 'id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'users',
        index: 'users_tenant_id_idx_41c0d441',
        columns: ['tenant_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'variant_colors',
        index: 'variant_colors_tenant_id_created_at_idx_282da036',
        columns: ['tenant_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'variant_colors',
        index: 'variant_colors_tenant_id_id_idx_621bc114',
        columns: ['tenant_id', 'id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'variant_colors',
        index: 'variant_colors_tenant_id_idx_41c0d441',
        columns: ['tenant_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'variant_sizes',
        index: 'variant_sizes_tenant_id_created_at_idx_282da036',
        columns: ['tenant_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'variant_sizes',
        index: 'variant_sizes_tenant_id_id_idx_621bc114',
        columns: ['tenant_id', 'id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'variant_sizes',
        index: 'variant_sizes_tenant_id_idx_41c0d441',
        columns: ['tenant_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'variant_units',
        index: 'variant_units_tenant_id_created_at_idx_282da036',
        columns: ['tenant_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'variant_units',
        index: 'variant_units_tenant_id_id_idx_621bc114',
        columns: ['tenant_id', 'id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'variant_units',
        index: 'variant_units_tenant_id_idx_41c0d441',
        columns: ['tenant_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'variant_weights',
        index: 'variant_weights_tenant_id_created_at_idx_282da036',
        columns: ['tenant_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'variant_weights',
        index: 'variant_weights_tenant_id_id_idx_621bc114',
        columns: ['tenant_id', 'id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'variant_weights',
        index: 'variant_weights_tenant_id_idx_41c0d441',
        columns: ['tenant_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'wastage',
        index: 'wastage_created_by_idx_e13bb8bf',
        columns: ['created_by'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'wastage',
        index: 'wastage_product_id_idx_22a2b7d2',
        columns: ['product_id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'wastage',
        index: 'wastage_tenant_id_created_at_idx_282da036',
        columns: ['tenant_id', 'created_at'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'wastage',
        index: 'wastage_tenant_id_id_idx_621bc114',
        columns: ['tenant_id', 'id'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'wastage',
        index: 'wastage_tenant_id_idx_41c0d441',
        columns: ['tenant_id'],
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'audit_logs',
        foreignKey: {
          name: 'audit_logs_tenant_id_fkey',
          columns: ['tenant_id'],
          references: { schema: 'public', table: 'tenants', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'audit_logs',
        foreignKey: {
          name: 'audit_logs_user_id_fkey',
          columns: ['user_id'],
          references: { schema: 'public', table: 'users', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'categories',
        foreignKey: {
          name: 'categories_tenant_id_fkey',
          columns: ['tenant_id'],
          references: { schema: 'public', table: 'tenants', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'customers',
        foreignKey: {
          name: 'customers_tenant_id_fkey',
          columns: ['tenant_id'],
          references: { schema: 'public', table: 'tenants', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'expense_categories',
        foreignKey: {
          name: 'expense_categories_tenant_id_fkey',
          columns: ['tenant_id'],
          references: { schema: 'public', table: 'tenants', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'expenses',
        foreignKey: {
          name: 'expenses_tenant_id_fkey',
          columns: ['tenant_id'],
          references: { schema: 'public', table: 'tenants', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'expenses',
        foreignKey: {
          name: 'expenses_category_id_fkey',
          columns: ['category_id'],
          references: { schema: 'public', table: 'expense_categories', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'expenses',
        foreignKey: {
          name: 'expenses_created_by_fkey',
          columns: ['created_by'],
          references: { schema: 'public', table: 'users', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'products',
        foreignKey: {
          name: 'products_tenant_id_fkey',
          columns: ['tenant_id'],
          references: { schema: 'public', table: 'tenants', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'products',
        foreignKey: {
          name: 'products_category_id_fkey',
          columns: ['category_id'],
          references: { schema: 'public', table: 'categories', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'products',
        foreignKey: {
          name: 'products_unit_id_fkey',
          columns: ['unit_id'],
          references: { schema: 'public', table: 'variant_units', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'products',
        foreignKey: {
          name: 'products_color_id_fkey',
          columns: ['color_id'],
          references: { schema: 'public', table: 'variant_colors', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'products',
        foreignKey: {
          name: 'products_size_id_fkey',
          columns: ['size_id'],
          references: { schema: 'public', table: 'variant_sizes', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'products',
        foreignKey: {
          name: 'products_weight_id_fkey',
          columns: ['weight_id'],
          references: { schema: 'public', table: 'variant_weights', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'returns',
        foreignKey: {
          name: 'returns_tenant_id_fkey',
          columns: ['tenant_id'],
          references: { schema: 'public', table: 'tenants', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'returns',
        foreignKey: {
          name: 'returns_sale_item_id_fkey',
          columns: ['sale_item_id'],
          references: { schema: 'public', table: 'sale_items', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'returns',
        foreignKey: {
          name: 'returns_created_by_fkey',
          columns: ['created_by'],
          references: { schema: 'public', table: 'users', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'sale_items',
        foreignKey: {
          name: 'sale_items_tenant_id_fkey',
          columns: ['tenant_id'],
          references: { schema: 'public', table: 'tenants', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'sale_items',
        foreignKey: {
          name: 'sale_items_sale_id_fkey',
          columns: ['sale_id'],
          references: { schema: 'public', table: 'sales', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'sale_items',
        foreignKey: {
          name: 'sale_items_product_id_fkey',
          columns: ['product_id'],
          references: { schema: 'public', table: 'products', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'sales',
        foreignKey: {
          name: 'sales_tenant_id_fkey',
          columns: ['tenant_id'],
          references: { schema: 'public', table: 'tenants', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'sales',
        foreignKey: {
          name: 'sales_customer_id_fkey',
          columns: ['customer_id'],
          references: { schema: 'public', table: 'customers', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'sales',
        foreignKey: {
          name: 'sales_sold_by_fkey',
          columns: ['sold_by'],
          references: { schema: 'public', table: 'users', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'stock_movements',
        foreignKey: {
          name: 'stock_movements_tenant_id_fkey',
          columns: ['tenant_id'],
          references: { schema: 'public', table: 'tenants', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'stock_movements',
        foreignKey: {
          name: 'stock_movements_product_id_fkey',
          columns: ['product_id'],
          references: { schema: 'public', table: 'products', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'stock_movements',
        foreignKey: {
          name: 'stock_movements_supplier_id_fkey',
          columns: ['supplier_id'],
          references: { schema: 'public', table: 'suppliers', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'stock_movements',
        foreignKey: {
          name: 'stock_movements_created_by_fkey',
          columns: ['created_by'],
          references: { schema: 'public', table: 'users', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'subscriptions',
        foreignKey: {
          name: 'subscriptions_tenant_id_fkey',
          columns: ['tenant_id'],
          references: { schema: 'public', table: 'tenants', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'supplier_payments',
        foreignKey: {
          name: 'supplier_payments_tenant_id_fkey',
          columns: ['tenant_id'],
          references: { schema: 'public', table: 'tenants', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'supplier_payments',
        foreignKey: {
          name: 'supplier_payments_supplier_id_fkey',
          columns: ['supplier_id'],
          references: { schema: 'public', table: 'suppliers', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'supplier_payments',
        foreignKey: {
          name: 'supplier_payments_created_by_fkey',
          columns: ['created_by'],
          references: { schema: 'public', table: 'users', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'suppliers',
        foreignKey: {
          name: 'suppliers_tenant_id_fkey',
          columns: ['tenant_id'],
          references: { schema: 'public', table: 'tenants', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'users',
        foreignKey: {
          name: 'users_tenant_id_fkey',
          columns: ['tenant_id'],
          references: { schema: 'public', table: 'tenants', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'variant_colors',
        foreignKey: {
          name: 'variant_colors_tenant_id_fkey',
          columns: ['tenant_id'],
          references: { schema: 'public', table: 'tenants', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'variant_sizes',
        foreignKey: {
          name: 'variant_sizes_tenant_id_fkey',
          columns: ['tenant_id'],
          references: { schema: 'public', table: 'tenants', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'variant_units',
        foreignKey: {
          name: 'variant_units_tenant_id_fkey',
          columns: ['tenant_id'],
          references: { schema: 'public', table: 'tenants', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'variant_weights',
        foreignKey: {
          name: 'variant_weights_tenant_id_fkey',
          columns: ['tenant_id'],
          references: { schema: 'public', table: 'tenants', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'wastage',
        foreignKey: {
          name: 'wastage_tenant_id_fkey',
          columns: ['tenant_id'],
          references: { schema: 'public', table: 'tenants', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'wastage',
        foreignKey: {
          name: 'wastage_product_id_fkey',
          columns: ['product_id'],
          references: { schema: 'public', table: 'products', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'wastage',
        foreignKey: {
          name: 'wastage_created_by_fkey',
          columns: ['created_by'],
          references: { schema: 'public', table: 'users', columns: ['id'] },
          onDelete: 'restrict',
        },
      }),
    ];
  }
}

MigrationCLI.run(import.meta.url, M);
